_wandb:
    value:
        cli_version: 0.25.1
        code_path: code/cfd-competition/kaggler/train.py
        e:
            arpnwqg1dnbcyxc85sntsz8bcal0bmal:
                args:
                    - --agent
                    - violet
                    - --wandb_name
                    - violet/baseline-resmlp-512x8
                codePath: cfd-competition/kaggler/train.py
                codePathLocal: train.py
                coreweave: {}
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "7679212060672"
                        used: "343472381952"
                email: tcapelle@wandb.com
                executable: /usr/bin/python
                git:
                    commit: fd1ef82f11ce812593157b941b573c78bdbaa617
                    remote: https://github.com/tcapelle/kagent.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Server Edition
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Server Edition
                      uuid: GPU-4a239bf3-54f8-f15c-59b2-0574ba1f23aa
                host: kagent-violet-674594545f-fjkc8
                memory:
                    total: "1080661295104"
                os: Linux-6.8.12-680-6063-coreweave-amd64-f81899c8-x86_64-with-glibc2.35
                program: /workspace/kagent/cfd-competition/kaggler/train.py
                python: CPython 3.10.12
                root: /workspace/kagent/cfd-competition/kaggler
                startedAt: "2026-03-18T22:32:46.698353Z"
                writerId: arpnwqg1dnbcyxc85sntsz8bcal0bmal
        m:
            - "1": global_step
              "6":
                - 3
              "7": []
            - "1": lr
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": val/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": val_in_dist/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": val_tandem_transfer/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": val_ood_cond/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": val_ood_re/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 7
                - 13
                - 15
                - 16
            "4": 3.10.12
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
agent:
    value: violet
batch_size:
    value: 4
debug:
    value: false
epochs:
    value: 50
lr:
    value: 0.0005
n_params:
    value: 8424451
splits_dir:
    value: /mnt/new-pvc/datasets/tandemfoil/splits
surf_weight:
    value: 10
train_samples:
    value: 1606
val_samples:
    value:
        val_in_dist: 76
        val_ood_cond: 102
        val_ood_re: 255
        val_tandem_transfer: 255
wandb_group:
    value: null
wandb_name:
    value: violet/baseline-resmlp-512x8
weight_decay:
    value: 0.0001
